### ISSUE TITLE
Error when running A2C

### ISSUE THREAD

**Issue by xiaobanni** [datawhalechina/easy-rl#26]
Thanks for this project.

An error is reported when running main.py in the A2C folder:
```
Start to train ! 
tensor([ 0.0307,  0.0015, -0.0309, -0.0313], device='cuda:0')
Traceback (most recent call last):
  File "G:/My First Paper/Code/easy-rl/codes/A2C/main.py", line 105, in <module>
    train(cfg,env,agent)
  File "G:/My First Paper/Code/easy-rl/codes/A2C/main.py", line 64, in train
    dist, value = agent.model(state)
  File "D:\2019Download\Anaconda\Anaconda\envs\IL\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:/My First Paper/Code/easy-rl/codes\A2C\model.py", line 34, in forward
    probs = self.actor(x)
  File "D:\2019Download\Anaconda\Anaconda\envs\IL\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\2019Download\Anaconda\Anaconda\envs\IL\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "D:\2019Download\Anaconda\Anaconda\envs\IL\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\2019Download\Anaconda\Anaconda\envs\IL\lib\site-packages\torch\nn\modules\activation.py", line 1200, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "D:\2019Download\Anaconda\Anaconda\envs\IL\lib\site-packages\torch\nn\functional.py", line 1583, in softmax
    ret = input.softmax(dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

Process finished with exit code 1
```

Looking forward to your guidance, thanks in advance.

**Comment by JohnJim0816** [comment]
A2C is updating in these two days, once finished I'll notice you

**Comment by JohnJim0816** [comment]
now is updated, but not performs well, I'll keep updating

**Comment by xiaobanni** [comment]
Great job, thank you very much.
